auth_magic: BxQUVKolaivKGOWCmtXm1EIC3SykobHU
password_hash_algos: sha256
shop_name: ミンカブMarketPlace
force_ssl: null
admin_allow_host: {  }
cookie_lifetime: 0
cookie_name: eccube
locale: ja
timezone: Asia/Tokyo
pageinrange: false
trusted_proxies_connection_only: true
trusted_proxies:
    - 127.0.0.1/8
    - '::1'
eccube_install: 1
